"""Package version and public schema identifiers."""

PACKAGE_VERSION = "3.4.0"
STATE_SCHEMA_VERSION = 1
PLAN_SCHEMA_VERSION = 1
PUBLIC_API_VERSION = 3
SESSION_SCHEMA_VERSION = 2
PROMPT_PLAN_SCHEMA_VERSION = 2
